### ISSUE TITLE
Strain colour settings

### ISSUE THREAD

**Issue by housw** [drpowell/FriPan#22]
Hi David, 

could you please tell me which file should I modify to color different groups of genomes. As I understand, I should use pan.strains file, but it doesn't work in my case. I saw the "strain-colour-scheme" was hard-coded as "raw", "cat10", "cat20a", "cat20b", "cat20c" in the pan.html file, so how can I change these values to my own groups. 

By the way, is the header "ID	Type	Order 1	Other" right in the pan.strains file? Is the "1" a typo? 

Thanks in advance!

**Comment by MathGon** [comment]
I have the same problem. Did you managed to solve it?

**Comment by housw** [comment]
Not really, I finally edited the svg files using inkscape.

**Comment by MathGon** [comment]
:(

**Comment by tseemann** [comment]
@housw @MathGon 

You can colour each genome by a column in the `pan.strains` file.  

1. Just add a column to it called anything you want (eg. `MyColour`) and then use valid CSS colour names (eg. `red`, `LemonChiffon`, 'Green`).  
2. Select *Strain colour:* to be `MyColour` and `Raw` (rather than `cat10` etc).
